export type Rarity = 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY';

export interface Fighter {
  id: string;
  name: string;
  title: string;
  emoji: string;
  color: string;
  glowColor: string;
  rarity: Rarity;
  /** Overall rating — higher = stronger in every combat stat */
  power: number;
  atk: number;
  hp: number;
  spd: number;
  luck: number;
  winRate: number;
  lore: string;
  specialty: string;
  badge: string;
  buff: { label: string; description: string };
  activity: number;
}

export const RARITY_COLOR: Record<Rarity, string> = {
  COMMON: '#8a92b2',
  RARE: '#00f0ff',
  EPIC: '#ff003c',
  LEGENDARY: '#fcee0a',
};

/**
 * Roster sorted weakest → strongest.
 * Rule: higher power ⇒ higher ATK, HP, SPD, and LCK.
 */
export const FIGHTERS: Fighter[] = [
  {
    id: 'pepe_prime',
    name: 'PEPE PRIME',
    title: 'The OG Amphibian',
    emoji: '🐸',
    color: '#00ff66',
    glowColor: '#00ff66',
    rarity: 'COMMON',
    power: 35,
    atk: 40,
    hp: 45,
    spd: 42,
    luck: 38,
    winRate: 48.2,
    lore: 'The original degen frog. Sunglasses permanently welded on after surviving three bear markets.',
    specialty: 'MEME_RESILIENCE',
    badge: 'P',
    buff: { label: 'Copium Shield +15%', description: 'Blocks 15% damage when HP drops below 40%' },
    activity: 91,
  },
  {
    id: 'street_rat',
    name: 'STREET RAT',
    title: 'Sewer Striker',
    emoji: '🐀',
    color: '#a0a0a0',
    glowColor: '#c0c0c0',
    rarity: 'COMMON',
    power: 38,
    atk: 43,
    hp: 48,
    spd: 46,
    luck: 40,
    winRate: 49.5,
    lore: 'Scrapyard scavenger who fights dirty and bites harder than most legends.',
    specialty: 'SCRAP_STRIKE',
    badge: 'R',
    buff: { label: 'Dirty Hit +12% SPD', description: '12% extra attack speed on opening rounds' },
    activity: 74,
  },
  {
    id: 'dogelord',
    name: 'DOGELORD',
    title: 'Much Combat. Very Wow.',
    emoji: '🐕',
    color: '#00a8ff',
    glowColor: '#00a8ff',
    rarity: 'COMMON',
    power: 42,
    atk: 48,
    hp: 52,
    spd: 50,
    luck: 44,
    winRate: 51.8,
    lore: 'Shiba supreme commander of the degen battalion. Blue visor scans every chart pattern.',
    specialty: 'HYPE_STRIKE',
    badge: 'D',
    buff: { label: 'Wow Factor +20% ATK', description: 'First strike deals 20% bonus damage' },
    activity: 88,
  },
  {
    id: 'mewtrix',
    name: 'MEWTRIX',
    title: 'Nine Lives Protocol',
    emoji: '🐱',
    color: '#b026ff',
    glowColor: '#b026ff',
    rarity: 'RARE',
    power: 48,
    atk: 54,
    hp: 58,
    spd: 56,
    luck: 50,
    winRate: 54.2,
    lore: 'Cybernetic feline that dodges rugs on instinct. Purple HUD tracks weakness vectors.',
    specialty: 'PHASE_DODGE',
    badge: 'M',
    buff: { label: 'Cat Reflex +25% SPD', description: '25% chance to dodge any attack' },
    activity: 84,
  },
  {
    id: 'based_frog',
    name: 'BASED FROG',
    title: 'Golden Armor Unit',
    emoji: '🐸',
    color: '#ffd700',
    glowColor: '#ffd700',
    rarity: 'RARE',
    power: 54,
    atk: 60,
    hp: 65,
    spd: 62,
    luck: 56,
    winRate: 56.8,
    lore: 'Pepe evolved. Plated in based gold exo-armor forged from liquidated shorts.',
    specialty: 'TANK_MODE',
    badge: 'B',
    buff: { label: 'Based Armor +30% HP', description: '30% damage reduction on first 3 hits' },
    activity: 80,
  },
  {
    id: 'giga_chad',
    name: 'GIGA CHAD',
    title: 'Jawline of Destiny',
    emoji: '🗿',
    color: '#ff8c00',
    glowColor: '#ffaa00',
    rarity: 'EPIC',
    power: 60,
    atk: 66,
    hp: 72,
    spd: 68,
    luck: 62,
    winRate: 58.4,
    lore: 'Sculpted from pure sigma energy. His jawline alone deals chip damage.',
    specialty: 'SIGMA_STARE',
    badge: 'G',
    buff: { label: 'Sigma +22% ATK', description: '22% damage boost when above 70% HP' },
    activity: 78,
  },
  {
    id: 'wojak',
    name: 'WOJAK',
    title: 'Feels Fighter',
    emoji: '😔',
    color: '#ff4da6',
    glowColor: '#ff4da6',
    rarity: 'EPIC',
    power: 66,
    atk: 72,
    hp: 78,
    spd: 74,
    luck: 68,
    winRate: 60.1,
    lore: 'The everyman warrior. Masked pain fuels devastating counter-attacks.',
    specialty: 'PAIN_CONVERT',
    badge: 'W',
    buff: { label: 'Feels Reversal +35%', description: 'Deals 35% more damage when below 50% HP' },
    activity: 77,
  },
  {
    id: 'bullx',
    name: 'BULLX',
    title: 'Market Gorer',
    emoji: '🐂',
    color: '#ff2200',
    glowColor: '#ff4400',
    rarity: 'EPIC',
    power: 74,
    atk: 80,
    hp: 85,
    spd: 80,
    luck: 74,
    winRate: 62.8,
    lore: 'Crimson bull forged in perpetual green candles. Horns pierce resistance levels.',
    specialty: 'BULL_RUSH',
    badge: 'X',
    buff: { label: 'Gore Charge +40% ATK', description: 'Charge attack ignores 40% of enemy defense' },
    activity: 75,
  },
  {
    id: 'diamond_degen',
    name: 'DIAMOND DEGEN',
    title: 'Hands of Eternity',
    emoji: '💎',
    color: '#00ffff',
    glowColor: '#00ffff',
    rarity: 'LEGENDARY',
    power: 82,
    atk: 88,
    hp: 92,
    spd: 86,
    luck: 80,
    winRate: 65.5,
    lore: 'Diamond hands crystallized into human form. Liquidation is a myth.',
    specialty: 'HODL_FORTRESS',
    badge: 'H',
    buff: { label: 'Diamond +35% HP', description: '35% HP boost when battle goes past round 6' },
    activity: 73,
  },
  {
    id: 'pingu',
    name: 'PINGU',
    title: 'Arctic Assassin',
    emoji: '🐧',
    color: '#00e5ff',
    glowColor: '#00e5ff',
    rarity: 'LEGENDARY',
    power: 88,
    atk: 92,
    hp: 96,
    spd: 90,
    luck: 84,
    winRate: 67.2,
    lore: 'Cold-blooded penguin operative. Cyan visor calculates kill shots in nanoseconds.',
    specialty: 'ICE_EXECUTION',
    badge: 'N',
    buff: { label: 'Frost Crit +45%', description: '45% crit chance on speed-based attacks' },
    activity: 72,
  },
  {
    id: 'rug_reaper',
    name: 'RUG REAPER',
    title: 'Dev Hunter',
    emoji: '💀',
    color: '#8800ff',
    glowColor: '#aa00ff',
    rarity: 'LEGENDARY',
    power: 94,
    atk: 96,
    hp: 98,
    spd: 94,
    luck: 88,
    winRate: 69.1,
    lore: 'Harvests dev wallets for sport. Scythe forged from abandoned liquidity pools.',
    specialty: 'SOUL_RUG',
    badge: 'K',
    buff: { label: 'Reap +48% Crit', description: '48% crit when opponent is below 30% HP' },
    activity: 85,
  },
  {
    id: 'zog',
    name: 'ZOG',
    title: 'Extraterrestrial Apex',
    emoji: '👽',
    color: '#c026ff',
    glowColor: '#e040ff',
    rarity: 'LEGENDARY',
    power: 99,
    atk: 99,
    hp: 99,
    spd: 96,
    luck: 92,
    winRate: 72.4,
    lore: 'The final boss of degen evolution. Alien intellect fused with meme market mastery.',
    specialty: 'COSMIC_DOMINANCE',
    badge: 'Z',
    buff: { label: 'Zog Beam +50% ALL', description: 'All stats boosted 50% in final battle phase' },
    activity: 96,
  },
];
